config/routes.rb
Rails.application.routes.draw do
root to: 'books#top'
resources :books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true

	validates :body,presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
  	@books = Book.all.order(created_at: :desc)
  	@book = Book.new
  end

  def new
  	@book = Book.new
  end

  def create
  	book = Book.new(book_params)
  	book.save
    if book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book
    else
      @books = Book.all
      @book = book
      render action: :index
    end
  end

  def show
    @book = Book.find(params[:id])
  end


  def edit
    @book = Book.find(params[:id])
  end

  def update
    book = Book.find(params[:id])
    book.update(book_params)
    if book.update(book_params)
      flash[:aaa] = "Book was successfully update."
    redirect_to book
  else
    @book = Book.find(params[:id])
    @book = book
    render action: :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    if book.destroy
      flash[:bbb] = "Book was successfully destroyed."
    redirect_to books_path
    else
      redirect_to books_path
    end
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1 class="edit-title">Editing Book</h1>
<% if @book.errors.any? %>
  <div class="error-box" id="error_explanation">
    <h2 class="error-title"><%= @book.errors.count %>erros prohibited this book from being saved:</h2>
 
    <ul class="error-text">
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
</div>

<%= form_for(@book) do |f| %>
<div class="edit-box">
	<%= f.label :title, "Title" %>
	<%= f.text_field :title %>
</div>
<div class="edit-box">
	<%= f.label :body, "Body" %>
	<%= f.text_area :body %>
</div>

	<%= f.submit 'Update Book' %>
<% end %>

<p class="edit-manu">
	<%= link_to"Show",book_path(@book) %> 
	| <%= link_to"Back", books_path %>
</p>

app/views/books/index.html.erb
<% if flash[:bbb] %>
 <p class="ok"><%= flash[:bbb] %></p>
<% end %>
<h1 class="index-title">Books</h1>

<table>
<thead>
  <tr>
	<th>Title</th>
	<th>Body</th>
  <th></th>
  <th></th>
  <th></th>
  </tr>
</thead>
<% @books.each do |book| %>
<tbody>
  <tr>
  	<td><%= book.title %></td>
  	<td><%= book.body %></td>
  	<td><%= link_to "Show",book_path(book.id) %></td>
  	<td><%= link_to "Edit",edit_book_path(book.id) %></td>
  	<td><%= link_to "Destroy",book_path(book.id),method: :delete, "data-confirm" => "Are you sure?" %></td>
  </tr>
</tbody>
<% end %>
 </table>










<h1 class="index-title">New book</h1>
<% if @book.errors.any? %>
  <div class="error-box" id="error_explanation">
    <h2 class="error-title"><%= @book.errors.count %>erros prohibited this book from being saved:</h2>
 
    <ul class=error-text>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

<%= form_for(@book) do |f| %>
<div class="new-box">
<%= f.label :title, "Title"%>
<%= f.text_field :title %>
</div>
<div class="new-box">
<%= f.label :body, "Body"%>
<%= f.text_area :body %>
</div>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_for(@book) do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>

<h4>Body</h4>
<%= f.text_area :body %>

<%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<% if flash[:notice] %>
	<p class="ok"><%= flash[:notice] %></p>
<% end %>
<% if flash[:aaa] %>
	<p class="ok"><%= flash[:aaa] %></p>
<% end %>
<p>
	<strong>Title:</strong>
	<%= @book.title %>
</p>
<p>
	<strong>Body:</strong>
	<%= @book.body %>
</p>

<p class="show-manu"><%= link_to "Edit",edit_book_path(@book) %> | <%= link_to "Back",books_path %></p>

app/views/books/top.html.erb
<h1>ようこそ　<storong>Bookers</storong> へ！</h1>

<p><strong>Bookers</strong>では、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>

<p><%= link_to"start",books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>